language: node_js
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
script:
  - npm run cover
  - npm run report
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "12"

